USE ictts;

DELETE FROM offices;
DELETE FROM regions;
ALTER TABLE regions AUTO_INCREMENT = 1;
ALTER TABLE offices AUTO_INCREMENT = 1;

INSERT INTO regions (code, name) VALUES
('ARMM', 'NFA ARMM Regional Office'),
('CARAGA', 'NFA CARAGA Regional Office'),
('CO', 'NFA Central Office'),
('NCR', 'NFA NCR Regional Office'),
('R1', 'NFA Region I Office'),
('R2', 'NFA Region II Office'),
('R3', 'NFA Region III Office'),
('R4', 'NFA Region IV Office'),
('R9', 'NFA Region IX Office'),
('R5', 'NFA Region V Office'),
('R6', 'NFA Region VI Office'),
('R7', 'NFA Region VII Office'),
('R8', 'NFA Region VIII Office'),
('R10', 'NFA Region X Office'),
('R11', 'NFA Region XI Office'),
('R12', 'NFA Region XII Office');

INSERT INTO offices (region_id, name, office_type) VALUES
(1, 'Maguindanao', 'Branch Office'),
(1, 'Basilan', 'Branch Office'),
(1, 'ARMM Regional Office', 'Regional Office'),
(1, 'Lanao del Sur', 'Branch Office'),
(2, 'Surigao del Sur', 'Branch Office'),
(2, 'Agusan del Sur', 'Branch Office'),
(2, 'NFA CARAGA Regional Office', 'Regional Office'),
(3, 'Administrative and General Services Department', 'Central Office'),
(3, 'Finance Department', 'Central Office'),
(3, 'Operations and Coordination Department', 'Central Office'),
(3, 'Legal Affairs Department', 'Central Office'),
(3, 'Corporate Planning and Management Services Deparment', 'Central Office'),
(3, 'Public Affairs Division', 'Central Office'),
(4, 'East District', 'District Office'),
(4, 'Central District', 'District Office'),
(4, 'NCR Regional Office', 'Regional Office'),
(5, 'Eastern Pangasinan', 'Branch Office'),
(5, 'Region I Office', 'Regional Office'),
(5, 'La Union', 'Branch Office'),
(5, 'Ilocos Norte', 'Branch Office'),
(6, 'Cagayan', 'Branch Office'),
(6, 'Nueva Vizcaya', 'Branch Office'),
(6, 'Region II Office', 'Regional Office'),
(6, 'Isabela', 'Branch Office'),
(7, 'Region III Office', 'Regional Office'),
(7, 'Bulacan', 'Branch Office'),
(7, 'Tarlac', 'Branch Office'),
(7, 'Pampanga', 'Branch Office'),
(7, 'Nueva Ecija', 'Branch Office'),
(8, 'Occidental Mindoro', 'Branch Office'),
(8, 'Palawan', 'Branch Office'),
(8, 'Oriental Mindoro', 'Branch Office'),
(8, 'Region IV Office', 'Regional Office'),
(8, 'Batangas', 'Branch Office'),
(8, 'Quezon', 'Branch Office'),
(8, 'Laguna', 'Branch Office'),
(9, 'Zamboanga Del Sur', 'Branch Office'),
(9, 'Region IX Office', 'Regional Office'),
(9, 'Zamboanga', 'Branch Office'),
(10, 'Region V Office', 'Regional Office'),
(10, 'Camarines Sur', 'Branch Office'),
(10, 'Sorsogon', 'Branch Office'),
(10, 'Albay', 'Branch Office'),
(11, 'Region VI Office', 'Regional Office'),
(11, 'Iloilo', 'Branch Office'),
(11, 'Capiz', 'Branch Office'),
(11, 'Negros Occidental', 'Branch Office'),
(12, 'Region VII Office', 'Regional Office'),
(12, 'Cebu', 'Branch Office'),
(12, 'Negros Oriental', 'Branch Office'),
(12, 'Bohol', 'Branch Office'),
(13, 'Leyte', 'Branch Office'),
(13, 'Region VIII Office', 'Regional Office'),
(13, 'Northern Samar', 'Branch Office'),
(14, 'Misamis Oriental', 'Branch Office'),
(14, 'Bukidnon', 'Branch Office'),
(14, 'Region X Office', 'Regional Office'),
(14, 'Lanao del Norte', 'Branch Office'),
(15, 'Davao Oriental', 'Branch Office'),
(15, 'Davao del Sur', 'Branch Office'),
(15, 'Region XI Office', 'Regional Office'),
(15, 'Davao del Norte', 'Branch Office'),
(16, 'Sultan Kudarat', 'Branch Office'),
(16, 'North Cotabato', 'Branch Office'),
(16, 'Region XII Office', 'Regional Office'),
(16, 'South Cotabato', 'Branch Office');
